name: Deploy Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm docs:build

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: okhsunrog.dev
          username: blogdeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: src/.vuepress/dist/*
          target: /var/www/blog/
          strip_components: 3
